export * from './actribute.js'
export * from './appliance.js'
export * from './apriori.js'
export * from './domitory.js'
export * from './generational.js'
export * from './onetomany.js'
export * from './sophistry.js'